### ISSUE TITLE
raze issue

### ISSUE THREAD

**Issue by Unikat2000** [fgsfds/Blood-Voxel-Pack#41]
Hi,

with the latest master branch download I have the problem that RAZE 1.1.2 crashes on startup with message "No volumes defined". Can anyone confirm?

**Comment by Dzierzan** [comment]
Hi, I tried Raze 1.1.2 and the master branch. No issues apart from animated voxels are not animated (works fine in NBlood and BloodGDX).

**Comment by Unikat2000** [comment]
Hi,
i tried a clean install of Raze with a fresh blood voxel pack.  The issue is still there and only effects OUWB and not Crytic Passage, which is pretty strange....

**Comment by Dzierzan** [comment]
I recommend opening the ticket in Raze github repo and posting there crashlog.

**Comment by Dzierzan** [comment]
Alright, it's fixed in the master branch of Raze, I am closing it.
