### ISSUE TITLE
the pack doesn't seem to work with NBlood anymore

### ISSUE THREAD

**Issue by tomatothesaddo** [fgsfds/Blood-Voxel-Pack#42]
a while back, I downloaded the pack and it worked fine with Nblood, but I redownloaded it and it didn't seem to work anymore :(

**Comment by Dzierzan** [comment]
Used the master branch? Used maybe autogenerated pre-release version? Did you put the zip in the autoload folder? Using the latest version of NBlood from autogenerated builds? I need details.

**Comment by tomatothesaddo** [comment]
I put the zip in the autoload folder, and I checked and made sure the enable autoload box was ticked

**Comment by Dzierzan** [comment]
I am not able to reproduce that as it works just fine for me

Can you check NBlood.log if voxels are even loaded?

Try removing models.ini if it is in your zip.

Do other autoload mods such as SmoothBlood work for you?

**Comment by tomatothesaddo** [comment]
I'll check the Nblood log, as for other autoload mods I don't really use any other than the model pack

**Comment by Dzierzan** [comment]
Please test my mod here and tell me if it works https://www.moddb.com/mods/smoothblood. At least we'll be able to rule this out.

Did you try removing that `models.ini`? Although I don't suspect that would cause any issues.

NBlood port is not clever enough to combine autoload mods together, it has to be done manually in Blood.def. BloodGDX or Raze can do it.

Can you provide pictures how your autoload folder looks like and NBlood window launcher?

**Comment by tomatothesaddo** [comment]
smooth blood works

as for the screenshots, 
this is my autoload folder
![Capture](https://user-images.githubusercontent.com/83978807/125477214-bfbe7fe0-0278-4b22-beb6-6bae3a720de9.PNG)

and the Nblood launch window looks like this
![Capture](https://user-images.githubusercontent.com/83978807/125478058-7cfa7d79-5200-4c6b-9719-45f0f06f42f0.PNG)

**Comment by Dzierzan** [comment]
Ok. So it loaded SmoothBlood fine. Remove that zip. What is that SGM file in your autoload folder? What is its purpose?

Die you try removing 'models.ini'?

**Comment by tomatothesaddo** [comment]
the sgm file is a soundfont, and I did try removing models.ini, to no avail.  here's the nblood.log
[nblood.log](https://github.com/fgsfds/Blood-Voxel-Pack/files/6811311/nblood.log)

**Comment by Dzierzan** [comment]
Do you have any loose DEF files in your Blood folder?

**Comment by tomatothesaddo** [comment]
not that I know of

**Comment by Dzierzan** [comment]
Ok, the last thing I can suggest is installing a fresh copy of Blood. I have no idea why it doesnt work for you and I asked around to find a possible reason.

Suffice to say, others dont have an issue either.

You could also try BloodGDX and tell me if it loads custom voxels.

**Comment by tomatothesaddo** [comment]
will do!

**Comment by tomatothesaddo** [comment]
after reinstalling Nblood, it worked fine, thanks!

**Comment by Dzierzan** [comment]
Great!
