### ISSUE TITLE
Compatibility with Coagulated

### ISSUE THREAD

**Issue by donizettilorenzo** [fgsfds/Blood-Voxel-Pack#43]
Can you make a compatible version (or directly add the content) with this?

https://www.moddb.com/mods/blood-coagulated/addons/blood-coagulated-11

Of course, before adding, contact the dev!

**Comment by Dzierzan** [comment]
A lot of his content was added already to this project. There's no need of contacting him as the license he used clearly states that his stuff can be used, edited, as long as the credits are provided, which are of course (just like the license of this project and other voxel packs).

Anyway, I am happy to add props, but when it comes to monsters, I prefer to be domain of his mod. Besides, he apparently aims to voxelize all props anyway, so we'll end with two Blood Voxel Pack projects, confusing I must say.

You have to edit def script on your own if you wanna combine these two mods, it's not really that hard. Note that both this and his project have the same voxels, there won't be conflicts though, just one will be chosen at start up.

**Comment by donizettilorenzo** [comment]
Thanks!
